name: deploy.yaml
on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: true
        target: prod
        tags: ghcr.io/${{ github.repository }}:latest
        secret-envs:
          CODECOV_TOKEN=CODECOV_TOKEN
        build-args: |
          GITHUB_SHA=${{ github.sha }}
          GITHUB_REPOSITORY=${{ github.repository }}
          GITHUB_REF_NAME=${{ github.ref_name }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
