name: execute.yml
on:
  workflow_dispatch:
  # Run every 3 hours at 15 minutes past the hour
  schedule:
    - cron: "15 0/3 * * *"

permissions: read-all

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out data
        uses: actions/checkout@v4
        with:
          path: data
          ref: data

      - name: Run
        run: Rscript main.R
        env:
          DATA_DIR: "data"

      - name: Create commit message
        id: commit_message_step
        run: |
          echo "commit_message=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Publish 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: data
          branch: data
          commit-message: ${{ steps.commit_message_step.outputs.commit_message }}
