name: execute.yml
on:
  # Run on deploy
  workflow_run:
    workflows: [deploy.yaml]
    types: [completed]
  # Run manually
  workflow_dispatch:
  # Run every 3 hours at 15 minutes past the hour
  schedule:
    - cron: "15 0/3 * * *"

permissions: read-all

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out data
        uses: actions/checkout@v4
        with:
          ref: data

      - name: Run
        id: run
        run: Rscript main.R
        working-directory: /product
        env:
          DATA_DIR: ${{ github.workspace }}

      - name: Publish 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: data
          commit-message: ${{ steps.run.outputs.commit_message }}
          
